### ISSUE TITLE
Add per notification customizable settings

### ISSUE THREAD

**Issue by Fredrik-Oberg** [ja1984/jackbox#11]
Should be able to add custom settings per each notification.

``` javascript
var notificationSettings = {
   time: 5, 
   classNames: "custom-class-name"
}
Jackbox.error("message", notificationSettings):
```

**Comment by godric3** [comment]
I think I can try do that, but got one question.
Overriding all settings of notification will be right, or should it only override specific settings?

**Comment by ja1984** [comment]
@godric3 i would say override all settings, so a notification should be able to take in the same settings object as the lib itself.

**Comment by Fredrik-Oberg** [comment]
Only override settings that you send in. 
I think you can use `Object.assign` for this to work.
Something in the line like this I believe would do it.

``` javascript
var createNotification = function (_message, type, customSettings) {
   var settings = Object.assign({}, lib.settings.notification, customSettings);
   var ttl = settings.time;
}
```

Then we will only overwrite the settings for that notification.

_\* edited javascript variable name_
