### ISSUE TITLE
Improve readme to explain css

### ISSUE THREAD

**Issue by ja1984** [ja1984/jackbox#18]

**Comment by ykl7** [comment]
@ja1984 What explanation of the CSS do you want in the README?

**Comment by sbshah97** [comment]
@ja1984 Could you explain how you'd like the README to be.

**Comment by ja1984** [comment]
@ykl7 @salman-bhai 

I'm thinking of an short explanation of the classes, what classes to change to change the visuals of the notification maybe?

**Comment by alxlark** [comment]
@ja1984 classes has good names so if you look at css you can read it like a book. It's not need add addition info in readme cause anyone can open file and see all that he/she need.

**Comment by ja1984** [comment]
@alxlark You're probably right, I will close this!
