### ISSUE TITLE
Change icons to svg

### ISSUE THREAD

**Issue by ja1984** [ja1984/jackbox#5]
The icons become blurry in phones

**Comment by alxlark** [comment]
Please provide list of all icons in lib

**Comment by ja1984** [comment]
The icosn for now are stored as base64 string in the css file.
I don't have the source icons on this computer, but I'm open to replace them.

We need an icons for:
- Success
- Errror
- Warning
- Information
- Dismiss (this I'm thinking of replacing with an text)

**Comment by AndreeaEne** [comment]
I propose replacing them with FontAwesome icons.

For example:
- Success: fa-check
- Error: fa-exclamation
- Warning: fa-exclamation-triangle
- Information: fa-info
- Dismiss: fa-times

**Comment by ja1984** [comment]
@AndreeaEne I've thought of that as well, the problem I see that in doing so we get dependent on a another library?
